//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotAndCold.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotAndCold.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopsie, the circle couldn&apos;t change its color. I&apos;ll leave the game once you click the button below..
        /// </summary>
        internal static string ErrorChangeColor {
            get {
                return ResourceManager.GetString("ErrorChangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopsie, I couldn&apos;t create a file on your computer. I&apos;ll leave the game once you click the button below..
        /// </summary>
        internal static string ErrorCreateFile {
            get {
                return ResourceManager.GetString("ErrorCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopsie, I couldn&apos;t start \&quot;My Computer\&quot;. I&apos;ll leave the game once you click the button below..
        /// </summary>
        internal static string ErrorExplorerStart {
            get {
                return ResourceManager.GetString("ErrorExplorerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopsie, something went wrong. I&apos;ll leave the game once you click the button below..
        /// </summary>
        internal static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopsie, I couldn&apos;t hide a file on your computer. I&apos;ll leave the game once you click the button below..
        /// </summary>
        internal static string ErrorHideFile {
            get {
                return ResourceManager.GetString("ErrorHideFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopsie, I couldn&apos;t open a file \&quot;YOU WON.txt\&quot;. I&apos;ll leave the game once you click the button below..
        /// </summary>
        internal static string ErrorOpenFile {
            get {
                return ResourceManager.GetString("ErrorOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU WON.txt.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really?? REALLY??? I&apos;ve put my heart into this, you know that, right? I tried to make you laugh!!! To bring something new to your life! Do you really want to leave this game?.
        /// </summary>
        internal static string QuestionExit {
            get {
                return ResourceManager.GetString("QuestionExit", resourceCulture);
            }
        }
    }
}
